export const TOGGLE_SETTING = 'TOGGLE_SETTING'
export const CHANGE_SETTING = 'CHANGE_SETTING'
export const CHANGE_THEME = 'CHANGE_THEME'

// Authentication Constant
export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNIN_USER = 'SIGNIN_USER'
export const ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT'
export const LOGOUT_USER = 'LOGOUT_USER'
export const COUNTRY_LIST = 'COUNTRY_LIST'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_DRAFT = 'CREATE_PROJECT_DRAFT'
export const CLEAR_PROJECT_DRAFT = 'CLEAR_PROJECT_DRAFT'
export const PROJECT_LIST = 'PROJECT_LIST'
export const SINGLE_PROJECT = 'SINGLE_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'

export const CREATE_GOAL = 'CREATE_GOAL'
export const CREATE_GOAL_DRAFT = 'CREATE_GOAL_DRAFT'
export const CLEAR_GOAL_DRAFT = 'CREATE_GOAL_DRAFT'
export const GOAL_LIST = 'GOAL_LIST'
export const SINGLE_GOAL = 'SINGLE_GOAL'
export const UPDATE_GOAL = 'UPDATE_GOAL'
export const ALL_GOALS = 'ALL_GOALS'

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_DRAFT = 'CREATE_TASK_DRAFT'
export const CLEAR_TASK_DRAFT = 'CREATE_TASK_DRAFT'
export const TASK_LIST = 'TASK_LIST'
export const SINGLE_TASK = 'SINGLE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const ALL_TASKS = 'ALL_TASKS'

